import {
  init,
  getDbEventos,
  getDbCategorias,
  getDbEventoCategoria,
  getDbEstados,
  getDbEstadoEventoCategoria,
  getDbEquiposGenerales,
  getDbEnfrentamientos,
  getDbTiposParticipacion,
  getDbReglasEvento,
  getDbEquiposInscritos,
  getDbIntegrantes,
  getDbEquiposInscritosGenerales,
} from "../infrastructure/database.js";
